/**
 * Handler for `oauth:exchange`. Performs the PKCE token-exchange leg
 * of the Claude Code OAuth flow on behalf of the control plane:
 *
 *   POST https://platform.claude.com/v1/oauth/token
 *     grant_type=authorization_code
 *     code=<from the operator's browser>
 *     code_verifier=<generated by the control, cached against session_id>
 *     client_id=9d1c250a-…   (Claude Code CLI client_id)
 *     redirect_uri=https://platform.claude.com/oauth/code/callback
 *
 * The point of doing this from the supervisor (instead of the
 * control's process) is the egress IP: each supervisor lives on the
 * customer's VPS so the request looks like an ordinary headless CLI
 * exchange from that VPS, not a centralised pattern from
 * `kujira.run`. The control already cached the verifier — it ships
 * it inline in the payload so the supervisor stays stateless.
 *
 * On success the ack carries the long-lived `access_token`. The
 * control encrypts and stores it; the supervisor never persists.
 */

import type { KJLogger } from '../../logger'
import {
    CLAUDE_OAUTH_CLIENT_ID,
    CLAUDE_OAUTH_REDIRECT_URI,
    CLAUDE_OAUTH_TOKEN_ENDPOINT,
    OAUTH_EXCHANGE_TIMEOUT_MS,
} from '../../oauth/constants'
import {
    type OAuthExchangeAck,
    type OAuthExchangePayload,
    WS_ERROR_CODES,
} from '../../protocol'

interface AnthropicTokenResponse {
    access_token: string
    refresh_token?: string
    token_type?: string
    expires_in?: number
    scope?: string
}

/**
 * Anthropic returns error bodies in TWO different shapes depending on
 * which layer rejected the request:
 *   - Validation/runtime (e.g. "Invalid request format"):
 *       { error: { type: "invalid_request_error", message: "..." } }
 *   - OAuth flow level (rate limit, invalid_grant):
 *       { error: "rate_limit_error", error_description: "..." }
 *       or sometimes the nested shape above with type="rate_limit_error".
 *
 * Be lenient and read whichever fields are present.
 */
interface AnthropicErrorResponse {
    error?: string | { type?: string; message?: string }
    error_description?: string
}

function extractErrorMessage(
    parsed: AnthropicErrorResponse | null,
    fallback: string
): string {
    if (!parsed?.error) return parsed?.error_description ?? fallback
    if (typeof parsed.error === 'string') {
        return parsed.error_description ?? parsed.error
    }
    return parsed.error.message ?? parsed.error.type ?? fallback
}

export interface OAuthExchangeHandlerDeps {
    logger: KJLogger
}

export class OAuthExchangeHandler {
    private readonly logger: KJLogger

    constructor(deps: OAuthExchangeHandlerDeps) {
        this.logger = deps.logger.child({ component: 'oauth-exchange' })
    }

    async handle(payload: OAuthExchangePayload): Promise<OAuthExchangeAck> {
        const { request_id, code: rawCode, code_verifier, state } = payload

        if (!rawCode || !code_verifier) {
            return {
                ok: false,
                error: {
                    code: WS_ERROR_CODES.INTERNAL_ERROR,
                    message: 'oauth:exchange requires both code and code_verifier',
                    retryable: false,
                },
            }
        }

        // claude.ai hands the operator a string shaped like
        // `<auth_code>#<state>` in headless mode. Anthropic's token
        // endpoint expects both halves as separate fields and rejects
        // bodies without `state` with "Invalid request format". Split
        // ourselves; if the operator pasted just the code, fall back
        // to the state the control passed us (== session_id).
        const [code, stateFromCode] = rawCode.split('#', 2)
        const effectiveState = stateFromCode || state

        // JSON body, NOT application/x-www-form-urlencoded — the
        // endpoint rejects form encoding with 400 "Invalid request
        // format". Confirmed against the reverse-engineered CLI.
        const body = JSON.stringify({
            grant_type: 'authorization_code',
            code,
            state: effectiveState,
            code_verifier,
            client_id: CLAUDE_OAUTH_CLIENT_ID,
            redirect_uri: CLAUDE_OAUTH_REDIRECT_URI,
        })

        // Debug: log shapes (not values) of every field so we can
        // diff against a known-good CLI exchange when something
        // breaks. Lengths reveal truncation/space/etc issues without
        // leaking the actual code or verifier.
        this.logger.info(
            {
                request_id,
                code_len: code.length,
                code_prefix: code.slice(0, 8),
                state_len: effectiveState?.length ?? 0,
                state_present: !!effectiveState,
                verifier_len: code_verifier.length,
            },
            'oauth exchange request shape'
        )

        const controller = new AbortController()
        const timer = setTimeout(() => controller.abort(), OAUTH_EXCHANGE_TIMEOUT_MS)

        let response: Response
        try {
            response = await fetch(CLAUDE_OAUTH_TOKEN_ENDPOINT, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Accept: 'application/json',
                },
                body,
                signal: controller.signal,
            })
        } catch (err) {
            const aborted = (err as Error)?.name === 'AbortError'
            this.logger.warn(
                { request_id, err: (err as Error).message, aborted },
                'oauth token endpoint unreachable'
            )
            return {
                ok: false,
                error: {
                    code: WS_ERROR_CODES.INTERNAL_ERROR,
                    message: aborted
                        ? `Anthropic did not respond within ${OAUTH_EXCHANGE_TIMEOUT_MS}ms`
                        : 'Could not reach Anthropic token endpoint',
                    retryable: true,
                },
            }
        } finally {
            clearTimeout(timer)
        }

        if (!response.ok) {
            const raw = await response.text().catch(() => '')
            let parsed: AnthropicErrorResponse | null = null
            try {
                parsed = JSON.parse(raw) as AnthropicErrorResponse
            } catch {
                // Body was not JSON; fall through with `raw` as the message.
            }
            const message = extractErrorMessage(
                parsed,
                raw || `Token endpoint returned ${response.status}`
            )
            this.logger.warn(
                {
                    request_id,
                    status: response.status,
                    error: parsed?.error,
                    description: parsed?.error_description,
                },
                'oauth exchange rejected by Anthropic'
            )
            return {
                ok: false,
                error: {
                    code: WS_ERROR_CODES.INTERNAL_ERROR,
                    message,
                    retryable: response.status >= 500,
                },
            }
        }

        let payload_response: AnthropicTokenResponse
        try {
            payload_response = (await response.json()) as AnthropicTokenResponse
        } catch (err) {
            this.logger.error({ request_id, err }, 'oauth response was not JSON')
            return {
                ok: false,
                error: {
                    code: WS_ERROR_CODES.INTERNAL_ERROR,
                    message: 'Token endpoint returned non-JSON',
                    retryable: false,
                },
            }
        }

        if (!payload_response.access_token) {
            return {
                ok: false,
                error: {
                    code: WS_ERROR_CODES.INTERNAL_ERROR,
                    message: 'Token endpoint response missing access_token',
                    retryable: false,
                },
            }
        }

        this.logger.info({ request_id }, 'oauth exchange ok')

        // We deliberately don't log scopes/expires/refresh — keep the
        // surface area small and the token itself out of structured
        // log fields.
        return {
            ok: true,
            access_token: payload_response.access_token,
        }
    }
}
